### ISSUE TITLE
OpenType

### ISSUE THREAD

**Issue by plutonet** [alexvoronov/gcdc-asn1#3]
I,m not able to configure a asn1 opentype object with gcdc-asn1 library
Has it already implemented or is in todo ?

this is an example of ASN

-- Regional extensions support
REG-EXT-ID-AND-TYPE ::= CLASS {
   &id     RegionId UNIQUE,
   &Type
 } WITH SYNTAX {&Type IDENTIFIED BY &id}

RegionalExtension {REG-EXT-ID-AND-TYPE : Set} ::= SEQUENCE {
   regionId     REG-EXT-ID-AND-TYPE.&id( {Set} ),
   regExtValue  REG-EXT-ID-AND-TYPE.&Type( {Set}{@regionId} )
}

**Comment by alexvoronov** [comment]
OpenType was not implemented in gcdc-asn1. There are currently no plans to do any further development, so I would not count on it appearing in this library any time soon. But feel free to open a pull request if you implement it :)
